-- Execute no SQL Editor do Supabase uma única vez.
create extension if not exists "pgcrypto";
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null default '',role text not null default 'professora' check(role in('professora','coordenadora','administradora')),institution text,class_name text,created_at timestamptz default now());
create table if not exists public.plans(id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,title text not null,status text not null default 'rascunho',start_date date,end_date date,content jsonb not null default '{}'::jsonb,updated_at timestamptz default now(),created_at timestamptz default now());
create table if not exists public.favorites(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,skill_code text not null,created_at timestamptz default now(),unique(user_id,skill_code));
create table if not exists public.evaluation_models(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,title text not null,content text not null,is_system boolean default false,created_at timestamptz default now());
alter table public.profiles enable row level security;alter table public.plans enable row level security;alter table public.favorites enable row level security;alter table public.evaluation_models enable row level security;
create policy "profile own select" on public.profiles for select using(auth.uid()=id);create policy "profile own update" on public.profiles for update using(auth.uid()=id);create policy "profile own insert" on public.profiles for insert with check(auth.uid()=id);
create policy "plans own all" on public.plans for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "favorites own all" on public.favorites for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "models read" on public.evaluation_models for select using(is_system or auth.uid()=user_id);create policy "models own insert" on public.evaluation_models for insert with check(auth.uid()=user_id);create policy "models own update" on public.evaluation_models for update using(auth.uid()=user_id);create policy "models own delete" on public.evaluation_models for delete using(auth.uid()=user_id);
insert into storage.buckets(id,name,public) values('activities','activities',false) on conflict(id) do nothing;
create policy "activities own read" on storage.objects for select using(bucket_id='activities' and auth.uid()::text=(storage.foldername(name))[1]);create policy "activities own upload" on storage.objects for insert with check(bucket_id='activities' and auth.uid()::text=(storage.foldername(name))[1]);create policy "activities own delete" on storage.objects for delete using(bucket_id='activities' and auth.uid()::text=(storage.foldername(name))[1]);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,name) values(new.id,coalesce(new.raw_user_meta_data->>'name',''));return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
